from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationScreen(object):
    def setupUi(self, RegistrationScreen):
        RegistrationScreen.setObjectName("RegistrationScreen")
        RegistrationScreen.resize(392, 600)
        RegistrationScreen.setMinimumSize(QtCore.QSize(392, 600))
        RegistrationScreen.setMaximumSize(QtCore.QSize(392, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/F1logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegistrationScreen.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(RegistrationScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 120, 274, 339))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_8.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit_8.setMaximumSize(QtCore.QSize(270, 30))
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout.addWidget(self.textEdit_8)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.textEdit_9 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_9.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit_9.setMaximumSize(QtCore.QSize(270, 30))
        self.textEdit_9.setObjectName("textEdit_9")
        self.verticalLayout_2.addWidget(self.textEdit_9)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.textEdit_10 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_10.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit_10.setMaximumSize(QtCore.QSize(270, 30))
        self.textEdit_10.setObjectName("textEdit_10")
        self.verticalLayout_3.addWidget(self.textEdit_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.textEdit_11 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_11.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit_11.setMaximumSize(QtCore.QSize(270, 30))
        self.textEdit_11.setObjectName("textEdit_11")
        self.verticalLayout_4.addWidget(self.textEdit_11)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_6.setMinimumSize(QtCore.QSize(270, 30))
        self.textEdit_6.setMaximumSize(QtCore.QSize(270, 30))
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_5.addWidget(self.textEdit_6)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(52, 101, 164);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(112, 480, 168, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        RegistrationScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegistrationScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 22))
        self.menubar.setObjectName("menubar")
        RegistrationScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegistrationScreen)
        self.statusbar.setObjectName("statusbar")
        RegistrationScreen.setStatusBar(self.statusbar)

        self.retranslateUi(RegistrationScreen)
        QtCore.QMetaObject.connectSlotsByName(RegistrationScreen)

    def retranslateUi(self, RegistrationScreen):
        _translate = QtCore.QCoreApplication.translate
        RegistrationScreen.setWindowTitle(_translate("RegistrationScreen", "MainWindow"))
        self.label.setText(_translate("RegistrationScreen", "Registration"))
        self.label_11.setText(_translate("RegistrationScreen", "Email:"))
        self.label_12.setText(_translate("RegistrationScreen", "Password:"))
        self.textEdit_9.setHtml(_translate("RegistrationScreen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("RegistrationScreen", "Number of races:"))
        self.label_14.setText(_translate("RegistrationScreen", "Points:"))
        self.label_9.setText(_translate("RegistrationScreen", "Team\'s email:"))
        self.label_6.setText(_translate("RegistrationScreen", "*Only if you are racer"))
        self.pushButton.setText(_translate("RegistrationScreen", "Back"))
        self.pushButton_2.setText(_translate("RegistrationScreen", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistrationScreen = QtWidgets.QMainWindow()
    ui = Ui_RegistrationScreen()
    ui.setupUi(RegistrationScreen)
    RegistrationScreen.show()
    sys.exit(app.exec_())
